import os
from pathlib import Path
from typing import Final

# --------------------------------------------------
# Base Directory
# --------------------------------------------------
# Absolute path to the backend project root.
# Used when constructing paths for static files,
# media uploads, templates, and other filesystem resources.

BASE_DIR: Final = Path(__file__).resolve().parent.parent.parent

# --------------------------------------------------
# Application Identity
# --------------------------------------------------
# Human-readable application name generated by Cookiecutter.
# Used for user-facing text such as account activation emails.

APP_NAME = "{{ cookiecutter.project_name }}"

# --------------------------------------------------
# Environment Variable Helpers
# --------------------------------------------------
# Helper functions for reading environment variables
# with proper validation and type conversion.
#
# get_env()       -> required string
# get_env_bool()  -> boolean
# get_env_list()  -> comma-separated list


def get_env(name: str, default: str | None = None) -> str:
    value = os.environ.get(name, default)

    if value is None:
        raise RuntimeError(f"Missing required environment variable: {name}")

    return value


def get_env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)

    if value is None:
        return default

    normalized_value = value.strip().lower()

    if normalized_value in {"true", "1", "yes", "on"}:
        return True

    if normalized_value in {"false", "0", "no", "off"}:
        return False

    raise RuntimeError(f"Environment variable {name} must be a boolean value.")


def get_env_list(
    name: str,
    default: str = "",
) -> list[str]:
    value = os.environ.get(name, default)

    return [item.strip() for item in value.split(",") if item.strip()]


# --------------------------------------------------
# Account Activation
# --------------------------------------------------
# PasswordResetTokenGenerator is reused for the initial
# account-activation workflow. Tokens expire according
# to Django's PASSWORD_RESET_TIMEOUT setting.

PASSWORD_RESET_TIMEOUT = int(
    get_env(
        "DJANGO_ACCOUNT_ACTIVATION_TIMEOUT_SECONDS",
        "86400",
    )
)

FRONTEND_PUBLIC_URL = get_env(
    "FRONTEND_PUBLIC_URL",
    "http://localhost:3000",
).rstrip("/")


# --------------------------------------------------
# Core Django Settings
# --------------------------------------------------
# Fundamental project settings loaded from the
# environment for different deployment environments
# such as development, staging, and production.

SECRET_KEY = get_env("DJANGO_SECRET_KEY")

DEBUG = get_env_bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = get_env_list("DJANGO_ALLOWED_HOSTS")

# --------------------------------------------------
# Installed Applications
# --------------------------------------------------
# The project uses a custom User model instead of
# Django's built-in auth.User.

DJANGO_APPS = [
    "django.contrib.admin",  # Django administration interface
    "django.contrib.auth",  # Authentication and permissions
    "django.contrib.contenttypes",  # Generic content types framework
    "django.contrib.sessions",  # Session framework
    "django.contrib.messages",  # Flash messages framework
    "django.contrib.staticfiles",  # Static file handling
]

THIRD_PARTY_APPS = [
    "rest_framework",
]

LOCAL_APPS = [
    "apps.core.apps.CoreConfig",  # Shared project utilities
    "apps.accounts.apps.AccountsConfig",  # Authentication and user management
    "apps.audit.apps.AuditConfig",  # Structured audit events
    "apps.reference_data.apps.ReferenceDataConfig",  # Controlled lookup data
]

INSTALLED_APPS = [
    *DJANGO_APPS,
    *THIRD_PARTY_APPS,
    *LOCAL_APPS,
]

# --------------------------------------------------
# Middleware
# --------------------------------------------------
# Middleware executes on every HTTP request and response.
#
# Order matters.
#
# Security
# Sessions
# Common HTTP processing
# CSRF protection
# Authentication
# Messages
# Clickjacking protection

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# --------------------------------------------------
# URL Configuration
# --------------------------------------------------
# Root URL configuration for the Django project.

ROOT_URLCONF = "config.urls"

# --------------------------------------------------
# Templates
# --------------------------------------------------
# Django template engine configuration.
#
# Primarily used for:
# - Django Admin
# - Email templates
# - Error pages
#
# The frontend is built with Next.js,
# so application pages are not rendered using
# Django templates.

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# --------------------------------------------------
# WSGI / ASGI Applications
# --------------------------------------------------
# WSGI:
#   Traditional synchronous deployments.
#
# ASGI:
#   Modern asynchronous deployments supporting
#   WebSockets, async views, and future real-time
#   features.

WSGI_APPLICATION = "config.wsgi.application"

ASGI_APPLICATION = "config.asgi.application"

# --------------------------------------------------
# Database
# --------------------------------------------------
# PostgreSQL configuration.
#
# Values are loaded from environment variables to
# support local development, CI/CD, staging, and
# production deployments.
#
# Connection pooling and health checks are enabled
# for long-running application containers.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_env("POSTGRES_DB"),
        "USER": get_env("POSTGRES_USER"),
        "PASSWORD": get_env("POSTGRES_PASSWORD"),
        "HOST": get_env("POSTGRES_HOST", "database"),
        "PORT": get_env("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
    }
}
# --------------------------------------------------
# Authentication
# --------------------------------------------------
# The application uses a custom User model instead of
# Django's built-in auth.User.
#
# Email is the primary login identifier.

AUTH_USER_MODEL = "accounts.User"

# --------------------------------------------------
# Password Validation
# --------------------------------------------------
# Password validation rules enforced during
# password creation and password changes.
#
# These validators help prevent weak passwords.

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]

# --------------------------------------------------
# Internationalization
# --------------------------------------------------
# Localization settings.
#
# The application timezone is configurable through Cookiecutter.
# using Asia/Manila as the default timezone.

LANGUAGE_CODE = "en-us"

TIME_ZONE = "{{ cookiecutter.default_timezone }}"

USE_I18N = True

USE_TZ = True

# --------------------------------------------------
# Session & CSRF
# --------------------------------------------------
# Session cookie configuration.
#
# SessionAuthentication stores authentication
# information inside secure HTTP cookies.
#
# CSRF protection prevents Cross-Site Request
# Forgery attacks.
#
# Additional production-only security settings
# such as SESSION_COOKIE_SECURE and
# CSRF_COOKIE_SECURE are configured in
# production.py.

SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_NAME = "csrftoken"
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

# --------------------------------------------------
# Static & Media Files
# --------------------------------------------------
# Static:
#   Version-controlled application assets
#   (CSS, JavaScript, images).
#
# Media:
#   User-uploaded application content
#   profile photos, leave attachments, and
#   supporting HR documents.

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# --------------------------------------------------
# Default Primary Key
# --------------------------------------------------
# Default primary key type for Django models.
#
# Individual applications may override this
# (for example, using UUID primary keys).

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------------------------------------
# Django REST Framework
# --------------------------------------------------
# Global DRF configuration.
#
# Authentication:
#   SessionAuthentication for authenticated users.
#
# Permissions:
#   Require authentication by default.
#
# Renderer:
#   JSON responses only.
#
# Parser:
#   Accept JSON request bodies.
#
# API Versioning:
#   Namespace-based versioning.

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_VERSIONING_CLASS": ("rest_framework.versioning.NamespaceVersioning"),
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1"],
}
