# Generated by Django 5.2 for the Cookiecutter reference-data foundation.

from collections.abc import Sequence
from typing import ClassVar
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[Sequence[tuple[str, str]]] = []

    operations = [
        migrations.CreateModel(
            name="ReferenceDataSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name", "code", "id"),
            },
        ),
        migrations.CreateModel(
            name="ReferenceDataValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="reference_data.referencedataset",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "name", "code", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="referencedatavalue",
            constraint=models.UniqueConstraint(
                fields=("reference_set", "code"),
                name="reference_value_set_code_uniq",
            ),
        ),
    ]
